# Generated by Django 4.2.20 on 2025-03-31 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_options_alter_course_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 31, 17, 41, 37, 341974), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/static/course/content/coursesImages', verbose_name='Иконка курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 31, 17, 41, 37, 341538), verbose_name='Дата добавления курса'),
        ),
    ]
