# Generated by Django 4.2.20 on 2025-03-31 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_comment_date_alter_course_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 31, 20, 11, 30, 140154), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='course',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 31, 20, 11, 30, 139739), verbose_name='Дата добавления курса'),
        ),
    ]
